name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: | 
          pip install -r requirements.txt

      - name: Debug test File
        run: |
          cat tests/test_app.py

      - name: Run Tests
        run: |
          python -m pytest

  build:
     needs: test
     runs-on: ubuntu-latest

     permissions:
       contents: read
       packages: write

     steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Log in to GHCR
         uses: docker/login-action@v3
         with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

       - name: Build Docker image
         run: |
           docker build -t ghcr.io/ridsbuddy/book-inventory-api:latest .

       - name: Push Docker image
         run: |
           docker push ghcr.io/ridsbuddy/book-inventory-api:latest

       - name: Setup SSH
         uses: webfactory/ssh-agent@v0.9.1
         with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

       - name: Deploy to EC2
         run: |
           ssh -o StrictHostKeyChecking=no \
             ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
               docker pull ghcr.io/ridsbuddy/book-inventory-api:latest &&
               docker rm -f book-inventory-api || true &&
               docker run -d \
                 --name book-inventory-api \
                 --restart unless-stopped \
                 -p 5000:5000 \
                 ghcr.io/ridsbuddy/book-inventory-api:latest
             "   

       - name: Health Check
         run: |
           ssh -o StrictHostKeyChecking=no \
             ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
             "curl --fail http://localhost:5000/health"
      
